"""Add symbol column to watchlist

Revision ID: 39569d1183f9
Revises: 
Create Date: 2026-01-02 22:52:47.584055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39569d1183f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prices')
    op.drop_table('stock_documents')
    op.drop_table('stocks')
    op.drop_table('chat_sessions')
    op.drop_table('watchlist_selected_item_history')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('documents_embedding_idx'), postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')

    op.drop_table('documents')
    op.drop_table('fundamentals')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('chat_messages_session_id_fkey'), type_='foreignkey')
        batch_op.drop_column('message_id')
        batch_op.drop_column('session_id')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('users_info', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               nullable=True)
        batch_op.alter_column('contact_no',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_unique_constraint(None, ['contact_no'])

    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol', sa.String(length=30), nullable=False))
        batch_op.drop_column('stock_symbol')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_symbol', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.drop_column('symbol')

    with op.batch_alter_table('users_info', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('contact_no',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('message_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('chat_messages_session_id_fkey'), 'chat_sessions', ['session_id'], ['session_id'], ondelete='CASCADE')
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('id')

    op.create_table('fundamentals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('pe', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True),
    sa.Column('roe', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True),
    sa.Column('debt_equity', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['stocks.symbol'], name=op.f('fk_fundamentals_symbol'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('fundamentals_pkey'))
    )
    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_pkey'))
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('documents_embedding_idx'), ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')

    op.create_table('watchlist_selected_item_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('symbol_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('selected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['selected'::character varying, 'unselected'::character varying]::text[])", name=op.f('watchlist_selected_item_history_status_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('watchlist_selected_item_history_pkey'))
    )
    op.create_table('chat_sessions',
    sa.Column('session_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_info.id'], name=op.f('chat_sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', name=op.f('chat_sessions_pkey'))
    )
    op.create_table('stocks',
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('sector', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('symbol', name='stocks_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('stock_documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('symbol', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('industry', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_documents_pkey'))
    )
    op.create_table('prices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('volume', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['stocks.symbol'], name=op.f('fk_prices_symbol'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('prices_pkey')),
    sa.UniqueConstraint('symbol', 'date', name=op.f('uq_price_per_day'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
